// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductCost = "product_cost"

// ProductCost mapped from table <product_cost>
type ProductCost struct {
	ID            int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64      `gorm:"column:user_id;not null" json:"user_id"`
	ProductType   string     `gorm:"column:product_type;not null" json:"product_type"`
	ProductID     int64      `gorm:"column:product_id;not null" json:"product_id"`
	PDate         string     `gorm:"column:p_date;not null" json:"p_date"`
	TotalCost7Day int64      `gorm:"column:total_cost_7day;not null" json:"total_cost_7day"`
	CreatedAt     *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP(1)" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP(1)" json:"updated_at"`
}

// TableName ProductCost's table name
func (*ProductCost) TableName() string {
	return TableNameProductCost
}
