// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User User table
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key ID" json:"id"`                              // Primary key ID
	Code      string         `gorm:"column:code;not null;comment:Business code" json:"code"`                                                // Business code
	Name      string         `gorm:"column:name;not null;comment:User name (advertiser or company name)" json:"name"`                       // User name (advertiser or company name)
	Type      int32          `gorm:"column:type;not null;comment:User type: 0=individual, 1=enterprise, 2=agency" json:"type"`              // User type: 0=individual, 1=enterprise, 2=agency
	Region    string         `gorm:"column:region;not null;comment:User region/location" json:"region"`                                     // User region/location
	Email     string         `gorm:"column:email;not null;comment:Contact email" json:"email"`                                              // Contact email
	Phone     string         `gorm:"column:phone;not null;comment:Contact phone" json:"phone"`                                              // Contact phone
	Status    *int32         `gorm:"column:status;not null;default:1;comment:User status: 0=inactive, 1=active, 2=suspended" json:"status"` // User status: 0=inactive, 1=active, 2=suspended
	Extra     string         `gorm:"column:extra;not null;comment:Extra information" json:"extra"`                                          // Extra information
	Version   int32          `gorm:"column:version;not null;comment:Optimistic lock version" json:"version"`                                // Optimistic lock version
	CreatedAt *time.Time     `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(1);comment:Creation time" json:"created_at"`       // Creation time
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:Update time" json:"updated_at"`                                               // Update time
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:Deletion time" json:"deleted_at"`                                             // Deletion time
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
