// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWebProduct = "web_product"

// WebProduct Web Product table
type WebProduct struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key ID" json:"id"`                        // Primary key ID
	Code      string         `gorm:"column:code;not null;comment:Business code" json:"code"`                                          // Business code
	Name      string         `gorm:"column:name;not null;comment:Name" json:"name"`                                                   // Name
	Mode      int32          `gorm:"column:mode;not null;comment:Mode" json:"mode"`                                                   // Mode
	Extra     string         `gorm:"column:extra;not null;comment:Extra information" json:"extra"`                                    // Extra information
	Version   int32          `gorm:"column:version;not null;comment:Optimistic lock version" json:"version"`                          // Optimistic lock version
	CreatedAt *time.Time     `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(1);comment:Creation time" json:"created_at"` // Creation time
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:Update time" json:"updated_at"`                                         // Update time
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:Deletion time" json:"deleted_at"`                                       // Deletion time
}

// TableName WebProduct's table name
func (*WebProduct) TableName() string {
	return TableNameWebProduct
}
