// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebProductUserRelation = "web_product_user_relation"

// WebProductUserRelation Product and user relation table
type WebProductUserRelation struct {
	ID         int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Auto-increment primary key" json:"id"`                   // Auto-increment primary key
	ProductID  int64      `gorm:"column:product_id;not null;comment:Product ID" json:"product_id"`                                        // Product ID
	UserID     int64      `gorm:"column:user_id;not null;comment:User ID" json:"user_id"`                                                 // User ID
	CreateDate *time.Time `gorm:"column:create_date;not null;default:CURRENT_TIMESTAMP(1);comment:Creation timestamp" json:"create_date"` // Creation timestamp
}

// TableName WebProductUserRelation's table name
func (*WebProductUserRelation) TableName() string {
	return TableNameWebProductUserRelation
}
