// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	ProductCost            *productCost
	User                   *user
	WebProduct             *webProduct
	WebProductUserRelation *webProductUserRelation
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ProductCost = &Q.ProductCost
	User = &Q.User
	WebProduct = &Q.WebProduct
	WebProductUserRelation = &Q.WebProductUserRelation
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		ProductCost:            newProductCost(db, opts...),
		User:                   newUser(db, opts...),
		WebProduct:             newWebProduct(db, opts...),
		WebProductUserRelation: newWebProductUserRelation(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ProductCost            productCost
	User                   user
	WebProduct             webProduct
	WebProductUserRelation webProductUserRelation
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		ProductCost:            q.ProductCost.clone(db),
		User:                   q.User.clone(db),
		WebProduct:             q.WebProduct.clone(db),
		WebProductUserRelation: q.WebProductUserRelation.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		ProductCost:            q.ProductCost.replaceDB(db),
		User:                   q.User.replaceDB(db),
		WebProduct:             q.WebProduct.replaceDB(db),
		WebProductUserRelation: q.WebProductUserRelation.replaceDB(db),
	}
}

type queryCtx struct {
	ProductCost            IProductCostDo
	User                   IUserDo
	WebProduct             IWebProductDo
	WebProductUserRelation IWebProductUserRelationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ProductCost:            q.ProductCost.WithContext(ctx),
		User:                   q.User.WithContext(ctx),
		WebProduct:             q.WebProduct.WithContext(ctx),
		WebProductUserRelation: q.WebProductUserRelation.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
